version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env-prod
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: app
    ports:
      - 80:8000
    depends_on:
      - db