"""clear

Revision ID: fe299ec4b4d3
Revises: 578b4b241d4e
Create Date: 2023-10-13 23:33:51.507843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fe299ec4b4d3'
down_revision: Union[str, None] = '578b4b241d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Atm', sa.Column('wheelchair', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('blind', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('nfc_for_bank_cards', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('qr_read', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('supports_usd', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('supports_charge_rub', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('supports_eur', sa.String(), nullable=True))
    op.add_column('Atm', sa.Column('supports_rub', sa.String(), nullable=True))
    op.drop_column('Atm', 'services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Atm', sa.Column('services', sqlite.JSON(), nullable=True))
    op.drop_column('Atm', 'supports_rub')
    op.drop_column('Atm', 'supports_eur')
    op.drop_column('Atm', 'supports_charge_rub')
    op.drop_column('Atm', 'supports_usd')
    op.drop_column('Atm', 'qr_read')
    op.drop_column('Atm', 'nfc_for_bank_cards')
    op.drop_column('Atm', 'blind')
    op.drop_column('Atm', 'wheelchair')
    # ### end Alembic commands ###
